/// <reference types="jest" />
/// <reference path="./lib/matchers-types.d.ts" />
export * from './lib/dom-selectors';
export * from './lib/http';
export * from './lib/mock';
export * from './lib/spectator';
export * from './lib/spectator-http';
export * from './lib/spectator-directive';
export * from './lib/spectator-service';
export * from './lib/spectator-host';
export * from './lib/spectator-routing';
export * from './lib/spectator-pipe';
