const rollupGlobals = {
  'date-fns'                     : 'date.fns',
  'codemirror'                   : 'codemirror',
  'ng2-nouislider/src/nouislider': 'nouislider',
  'svg-pan-zoom'                 : 'svg.pan.zoom',
  'tslib'                        : 'tslib',
  'ramda'                        : 'ramda',
  'jquery'                       : '$',
  '$'                            : '$',
  jquery                         : 'jQuery',
  'file-saver'                   : 'file-saver',
  'lodash'                       : 'lodash',

  'd3'            : 'd3',
  'd3-ease'       : 'd3.ease',
  'd3-interpolate': 'd3.interpolate',
  'd3-scale'      : 'd3.scale',
  'd3-selection'  : 'd3.selection',

  '@angular/animations'                 : 'ng.animations',
  '@angular/core'                       : 'ng.core',
  '@angular/common'                     : 'ng.common',
  '@angular/common/http'                : 'ng.common',
  '@angular/forms'                      : 'ng.forms',
  '@angular/http'                       : 'ng.http',
  '@angular/router'                     : 'ng.router',
  '@angular/platform-browser'           : 'ng.platformBrowser',
  '@angular/platform-server'            : 'ng.platformServer',
  '@angular/platform-browser-dynamic'   : 'ng.platformBrowserDynamic',
  '@angular/platform-browser/animations': 'ng.platformBrowser.animations',
  '@angular/core/testing'               : 'ng.core.testing',
  '@angular/common/testing'             : 'ng.common.testing',
  '@angular/http/testing'               : 'ng.http.testing',
  '@angular/common/http/testing'        : 'ng.http.testing',
  '@angular/material'                   : 'ng.material',
  '@angular/cdk'                        : 'ng.cdk',
  '@angular/cdk/portal'                 : 'ng.cdk.portal',
  '@angular/cdk/coercion'               : 'ng.cdk.coercion',
  '@angular/cdk/layout'                 : 'ng.cdk.layout',
  '@angular/cdk/platform'               : 'ng.cdk.platform',
  '@angular/cdk/testing'                : 'ng.cdk.testing',
  '@angular/cdk/overlay'                : 'ng.cdk.overlay',
  '@angular/material-examples'          : 'ng.materialExamples',

  'rxjs/BehaviorSubject'           : 'Rx',
  'rxjs/Observable'                : 'Rx',
  'rxjs/Subject'                   : 'Rx',
  'rxjs/Subscription'              : 'Rx',
  'rxjs/Observer'                  : 'Rx',
  'rxjs/Scheduler'                 : 'Rx',
  'rxjs/observable/combineLatest'  : 'Rx.Observable',
  'rxjs/observable/forkJoin'       : 'Rx.Observable',
  'rxjs/observable/fromEvent'      : 'Rx.Observable',
  'rxjs/observable/merge'          : 'Rx.Observable',
  'rxjs/observable/ErrorObservable': 'Rx.Observable',
  'rxjs/observable/of'             : 'Rx.Observable',
  'rxjs/observable/throw'          : 'Rx.Observable',
  'rxjs/observable/defer'          : 'Rx.Observable',
  'rxjs/operator/auditTime'        : 'Rx.Observable.prototype',
  'rxjs/operator/catch'            : 'Rx.Observable.prototype',
  'rxjs/operator/debounceTime'     : 'Rx.Observable.prototype',
  'rxjs/operator/do'               : 'Rx.Observable.prototype',
  'rxjs/operator/filter'           : 'Rx.Observable.prototype',
  'rxjs/operator/finally'          : 'Rx.Observable.prototype',
  'rxjs/operator/first'            : 'Rx.Observable.prototype',
  'rxjs/operator/let'              : 'Rx.Observable.prototype',
  'rxjs/operator/map'              : 'Rx.Observable.prototype',
  'rxjs/operator/share'            : 'Rx.Observable.prototype',
  'rxjs/operator/startWith'        : 'Rx.Observable.prototype',
  'rxjs/operator/switchMap'        : 'Rx.Observable.prototype',
  'rxjs/operator/takeUntil'        : 'Rx.Observable.prototype',
  'rxjs/operator/toPromise'        : 'Rx.Observable.prototype',
  'rxjs/operators'                 : 'Rx.Observable',

  'rxjs/add/observable/fromEvent'         : 'Rx.Observable',
  'rxjs/add/observable/interval'          : 'Rx.Observable',
  'rxjs/add/observable/merge'             : 'Rx.Observable',
  'rxjs/add/observable/of'                : 'Rx.Observable',
  'rxjs/add/observable/throw'             : 'Rx.Observable',
  'rxjs/add/operator/catch'               : 'Rx.Observable.prototype',
  'rxjs/add/operator/debounceTime'        : 'Rx.Observable.prototype',
  'rxjs/add/operator/delay'               : 'Rx.Observable.prototype',
  'rxjs/add/operator/distinctUntilChanged': 'Rx.Observable.prototype',
  'rxjs/add/operator/do'                  : 'Rx.Observable.prototype',
  'rxjs/add/operator/filter'              : 'Rx.Observable.prototype',
  'rxjs/add/operator/finally'             : 'Rx.Observable.prototype',
  'rxjs/add/operator/first'               : 'Rx.Observable.prototype',
  'rxjs/add/operator/last'                : 'Rx.Observable.prototype',
  'rxjs/add/operator/map'                 : 'Rx.Observable.prototype',
  'rxjs/add/operator/startWith'           : 'Rx.Observable.prototype',
  'rxjs/add/operator/switchMap'           : 'Rx.Observable.prototype',
  'rxjs/add/operator/takeUntil'           : 'Rx.Observable.prototype',
  'rxjs/scheduler/AnimationFrameScheduler': 'Rx',
  'rxjs/scheduler/animationFrame'         : 'Rx',

  '@ng-bootstrap/ng-bootstrap'                         : 'ngb.ngb',
  '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module'  : 'ngb.tooltip',
  '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module': 'ngb.dropdown',
  '@ng-bootstrap/ng-bootstrap/popover/popover.module'  : 'ngb.popover',
};

module.exports = rollupGlobals;
