name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  yarn-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: cache
        name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: [yarn-install]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Build
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  test:
    runs-on: ubuntu-latest
    needs: [yarn-install]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Test
        run: yarn test:ci
      - name: Lint
        run: yarn lint
